included:
  - Sources
  - Tests

excluded:
  - .build

line_length:
  warning: 120
  error: 150
  ignores_comments: true

disabled_rules:
  - trailing_comma

opt_in_rules:
  - force_unwrapping
  - empty_count

type_name:
  min_length: 2
  max_length: 50

identifier_name:
  min_length: 1
  max_length: 50
